# --------------------------------------------------------------------
#+TITLE:   Initial value problem for a viscous liquid layer
#+AUTHOR: Clément & Arnaud
#+STARTUP: indent latexpreview
#+LATEX_HEADER: \usepackage[round]{natbib} \usepackage{bm}  \setlength{\parindent}{0}
#+OPTIONS: toc:nil
# --------------------------------------------------------------------

citet:Cortelezzi1981 propose a derivation of the equations governing
the initial value problem for a disturbed layer of viscous fluid,
considering both the effects of gravity and surface tension. We here
propose to revisit this paper by following an alternative derivation
based on the ideas of citet:Prosperetti1976. More specifically we
split the dynamical variables into a potential and a viscous
contribution. We restrict the analysis to a 2D setting, and note that
all the obtained results can be directly transposed to 3D, see
citet:Cortelezzi1981.


* Vorticity production

The vorticity is directed along $\boldsymbol e_y$:
\begin{equation}
\boldsymbol \omega = \left(
\begin{array}{c}
\omega_x \\
\omega_y \\
\omega_z
\end{array}
\right) =
\left.
\begin{array}{c}
\partial_x \\
0 \\
\partial_z
\end{array}
\right|
\times
\left|
\begin{array}{c}
u \\
0 \\
w
\end{array}
\right. =
\left(
\frac{\partial u}{\partial z} - 
\frac{\partial w}{\partial x}
\right) \boldsymbol e_y
\end{equation}
Introducing the viscous shear stress $\tau_{xz} = \mu \left(
\frac{\partial u}{\partial z} + \frac{\partial w}{\partial x} \right)$
we can express the vorticity in terms of viscous shear stress:
\begin{equation}
\omega_y = \frac{\tau_{xz}}{\mu} - 2 \frac{\partial w}{\partial x}
\end{equation}
At the free surface, the tangential shear stress vanishes so
$\omega_y = - 2 \frac{\partial w}{\partial x}$ there.
This can be further reexpressed in terms of local free surface slope
variation with the help of the linearised kinematic condition $w =
\frac{\partial \eta}{\partial t}$, where $\eta(x,t)$ denotes the free
surface position. This relation reveals that vorticity production at
the free surface is equal to the time variation of the local slope:
\begin{equation}
\omega_y = - 2 \frac{\partial^2 \eta}{\partial x \partial t}
\end{equation}

* Problem splitting: the potential and the viscous

The equations governing the problem are associated with mass
conservation:
\begin{equation}
\nabla \cdot \boldsymbol u = 0,
\end{equation}
and momentum conservation:
\begin{equation}
\frac{\partial \boldsymbol u}{\partial t} = - \frac{1}{\rho} \nabla p + \nu \nabla^2\boldsymbol u - g \boldsymbol e_z.
\end{equation}

** Kinematical description of the interface

The interface is tracked at all times with the help of the color
function $F(x,z,t) = z - \eta(x,t)$ which cancels at the free
surface. We here look for /standing waves/ for which $\eta(x,t) = a(t)
\cos(kx)$.
From this definition we can derive the expression of the
/linearised/ outward normal:
\begin{equation}
\boldsymbol n = \frac{\nabla F}{\|\nabla F\|} \simeq \left(k a(t) \sin (kx), 1 \right)
\end{equation}
This approximation is valid as long as the /amplitude/ (not the layer
thickness!) is small in front of the wavelength (i.e. $k a(t) \ll 1$).
Finally we require the function $F$ to satisfy the /kinematical
boundary condition/ $DF/Dt=0$. Linearisation yields to flatten this
condition at $z=0$:
\begin{equation}
\frac{\partial F}{\partial t} + w \frac{\partial F}{\partial z} = 0 \quad \text{on z = 0}
\end{equation}

** Dynamical boundary conditions

At the free surface, the normal stress jump is balanced by surface
tension:
\begin{equation}
-p + 2 \mu \frac{\partial w}{\partial z} = - \gamma \nabla \cdot
\boldsymbol n \quad \text{on} \quad F = 0
\end{equation}
and the shear stress is required to vanish (/free surface/ assumption):
\begin{equation}
\tau_{xz} = 0 \quad \text{on} \quad F = 0
\end{equation}

** Potential and viscous parts

As demonstrated in citet:Prosperetti1976 it is convenient to split the
dynamical fields into a /potential/ and a /viscous/ part:
\begin{equation}
\boldsymbol u = \boldsymbol u_p + \boldsymbol u_v \quad ; \quad p = p_p + p_v
\end{equation}

bibliographystyle:abbrvnat
bibliography:suppl_note.bib
