# --------------------------------------------------------------------
#+TITLE:   Initial value problem for a viscous liquid layer
#+AUTHOR: Clément & Arnaud
#+STARTUP: indent latexpreview
#+LATEX_HEADER: \usepackage[text={18cm,26cm},centering]{geometry}
#+LATEX_HEADER: \usepackage{mathtools} \usepackage[round]{natbib} \usepackage{bm}  \usepackage{cancel} \setlength{\parindent}{0pt}
#+OPTIONS: toc:nil H:4
# --------------------------------------------------------------------

#+BEGIN_EXPORT html
<script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        TeX: {extensions: ["cancel.js"]},
        tex2jax: {
          inlineMath: [ ['$','$'], ['\\(','\\)'] ],
          processEscapes: true
        }
      });
</script>
<script type="text/x-mathjax-config">
MathJax.Extension['TeX/subequations'] = {
  version: "1.0.0",
  subEq: false,
  subNo: 0
};

MathJax.Hub.Register.StartupHook('TeX Jax Ready', function () {
  var TEX = MathJax.InputJax.TeX,
      TEXDEF = TEX.Definitions;
  var SUBEQ = MathJax.Extension['TeX/subequations'];
  var CONFIG = MathJax.Hub.config.TeX.equationNumbers;

  SUBEQ.oldFormat = CONFIG.formatNumber;
  CONFIG.formatNumber = function (n) {
    n = SUBEQ.oldFormat(n);
    if (!SUBEQ.subEq) return n;
    MathJax.Extension['TeX/AMSmath'].number--;
    var m = ++SUBEQ.subNo;
    return n + String.fromCharCode(0x60 + m);
  };

  TEXDEF.Add({
    environment: {
      subequations: ['SubEquationsBegin', 'SubEquationsEnd']
    }
  });

  TEX.Parse.Augment({
    SubEquationsBegin: function (begin) {
      SUBEQ.subEq = true;
      SUBEQ.subNo = 0;
      return begin;
    },
    SubEquationsEnd: function (begin, row) {
      SUBEQ.subEq = false;
      MathJax.Extension['TeX/AMSmath'].number++;
      return row;
    }
  });

  MathJax.Hub.Startup.signal.Post("TeX subequations Ready");
});
</script>
#+END_EXPORT

citet:Cortelezzi1981 propose a derivation of the equations governing
the initial value problem for a disturbed layer of viscous fluid,
considering both the effects of gravity and surface tension. We here
propose to revisit this paper by following an alternative derivation
based on the ideas of citet:Prosperetti1976. More specifically we
split the dynamical variables into a potential and a viscous
contribution. We restrict the analysis to a 2D setting, and note that
all the obtained results can be directly transposed to 3D, see
citet:Cortelezzi1981.

<<toc>>
#+TOC: headlines 2

* Vorticity production at the free surface

The vorticity is directed along $\boldsymbol e_y$:
#+BEGIN_LATEX
\begin{equation}
\boldsymbol \omega = \left(
\begin{array}{c}
\omega_x \\
\omega_y \\
\omega_z
\end{array}
\right) =
\left.
\begin{array}{c}
\partial_x \\
0 \\
\partial_z
\end{array}
\right|
\times
\left|
\begin{array}{c}
u \\
0 \\
w
\end{array}
\right. =
\left(
\frac{\partial u}{\partial z} - 
\frac{\partial w}{\partial x}
\right) \boldsymbol e_y
\end{equation}
#+END_LATEX
Introducing the viscous shear stress $\tau_{xz} = \mu \left(
\frac{\partial u}{\partial z} + \frac{\partial w}{\partial x} \right)$
we can express the vorticity in terms of viscous shear stress:
\begin{equation}
\omega_y = \frac{\tau_{xz}}{\mu} - 2 \frac{\partial w}{\partial x}
\end{equation}
At the free surface, the tangential shear stress vanishes so
$\omega_y = - 2 \frac{\partial w}{\partial x}$ there.
This can be further reexpressed in terms of local free surface slope
variation with the help of the linearised kinematic condition $w =
\frac{\partial \eta}{\partial t}$,
where $\eta(x,t)$ denotes the free surface position. This relation
reveals that vorticity production at the free surface is equal to the
time variation of the local slope:
\begin{equation}
\omega_y = - 2 \frac{\partial^2 \eta}{\partial x \partial t} \label{eq:vorticity_production_interface}
\end{equation}

* Problem splitting: the potential and the viscous

The equations governing the problem are associated with mass
conservation:
\begin{equation}
\nabla \cdot \boldsymbol u = 0,
\end{equation}
and momentum conservation:
\begin{equation}
\frac{\partial \boldsymbol u}{\partial t} = - \frac{1}{\rho} \nabla p + \nu \nabla^2\boldsymbol u - g \boldsymbol e_z.
\end{equation}

** Kinematical description of the interface

The interface is tracked at all times with the help of the color
function $F(x,z,t) = z - \eta(x,t)$ which cancels at the free
surface. We here look for /standing waves/ for which $\eta(x,t) = a(t) \cos(kx)$.
From this definition we can derive the expression of the /linearised/ outward
normal:
\begin{equation}
\boldsymbol n = \frac{\nabla F}{\|\nabla F\|} \simeq \left(k a(t) \sin (kx), 1 \right)
\end{equation}
This approximation is valid as long as the /amplitude/ (not the layer
thickness!) is small in front of the wavelength (i.e. $k a(t) \ll 1$).
Finally we require the function $F$ to satisfy the /kinematical
boundary condition/ $DF/Dt=0$. Linearisation yields to flatten this
condition at $z=0$:
\begin{equation}
\frac{\partial F}{\partial t} + w \frac{\partial F}{\partial z} = 0 \quad \text{on} \quad z = 0
\end{equation}

** Dynamical boundary conditions

*** At the free surface

At the free surface, the normal stress jump is balanced by surface
tension:
\begin{equation}
-p + 2 \mu \frac{\partial w}{\partial z} = - \gamma \nabla \cdot
\boldsymbol n \quad \text{on} \quad F = 0
\label{eq:normalstressjump}
\end{equation}
and the shear stress is required to vanish (/free surface/ assumption):
\begin{equation}
\tau_{xz} = 0 \quad \text{on} \quad F = 0
\end{equation}

*** At the bottom

Impermeability and adherence impose:
\begin{equation}
u(z=-h) = w(z=-h) = 0
\end{equation}

** Potential and viscous parts

As demonstrated in citet:Prosperetti1976 it is convenient to split the
dynamical fields into a /potential/ and a /viscous/ part:
\begin{equation}
\boldsymbol u = \boldsymbol u_p + \boldsymbol u_v \quad ; \quad p = p_p + p_v
\end{equation}

**** $\rhd$ The potential problem.
:PROPERTIES:
:UNNUMBERED: t
:END:
$(\boldsymbol u_p,p_p)$ is solution to the following problem

\begin{subequations}
\begin{align}
&\boldsymbol u_p = \nabla \phi,\\[1em]
&\nabla^2 \phi = 0,\\[1em]
&\frac{\partial \boldsymbol u_p}{\partial t} = -\frac{1}{\rho} \nabla p_p - g \boldsymbol e_z,  \\[1em]
&\frac{\partial F}{\partial t} + w_p \frac{\partial F}{\partial z} = 0 \quad \text{on} \quad z = 0, \label{eq:kinematic_potential} \\[1em]
&\frac{\partial \phi}{\partial z} = 0  \quad \text{on} \quad z = -h.
\end{align}
\end{subequations}

Note that eqref:eq:kinematic_potential reads
\begin{equation}
w_p = \frac{\partial \eta}{\partial t} \label{eq:kinematic_potential_simplified}
\end{equation}
**** $\rhd$ The viscous correction.
:PROPERTIES:
:UNNUMBERED: t
:END:
$(\boldsymbol u_v,p_v)$ are then governed by the following equations:
\begin{subequations}
\begin{eqnarray}
&&\nabla \cdot \boldsymbol u_v = 0,\label{eq:viscous_system_a}\\[1em]
&&\frac{\partial \boldsymbol u_v}{\partial t} = -\frac{1}{\rho} \nabla p_v + \nu \nabla^2 \boldsymbol u_v,\label{eq:momentum_viscous}\\[1em]
&&w_v \frac{\partial F}{\partial z} = 0 \quad \text{on} \quad z = 0,\label{eq:kinematic_viscous}\\[1em]
&&u = u_p + u_v = 0  \quad \text{on} \quad z = -h.\label{eq:viscous_system_d}
\end{eqnarray}
\end{subequations}
and now the kinematical condition for the viscous problem eqref:eq:kinematic_viscous reads
\begin{equation}
w_v = 0  \quad \text{on} \quad z = 0
\end{equation}

** The potential solution

As we look for a standing wave-like solution, we search for a general
solution for the potential by exploiting variable separation. The
structure of the kinematical boundary condition
eqref:eq:kinematic_potential_simplified motivates the following
ansatz:
\begin{equation}
\phi(x,z,t) = F(z) \dot a(t) \cos (kx)
\end{equation}
eqref:eq:kinematic_potential_simplified and impermeability at the
bottom allow to precise $F(z)$:
\begin{equation}
\phi(x,z,t) = \frac{1}{k} \dot a(t) \underbrace{\frac{\cosh\left(k(z+h)\right)}{\sinh(kh)}}_{\underset{h\to\infty}{\to} \,e^{kz}}\cos(kx)
\end{equation}
The linearised form of Bernoulli equation  $p + \rho \frac{\partial
\phi}{\partial t} + \rho g z = 0$
associated with the expression for $\phi$ allows to deduce the pressure
field:
\begin{equation}
p_p(x,z,t) = -\rho\left(gz + \frac{1}{k} \frac{\mathrm d^2 a}{\mathrm dt^2} \frac{\cosh\left(k(z+h)\right)}{\sinh(kh)}\cos(kx)\right)
\end{equation}
These two expressions reduce to citeauthor:Prosperetti1976 expressions
in the deep layer limit. In the classic potential problem, $a(t)$ is
determined by the dynamical boundary condition on the free surface,
but as in the present problem both the viscous and the potential parts
are intertwined, this determination is postponed.

** The viscous solution

Let's turn now to the system of equations describing the viscous part
eqref:eq:viscous_system_a - eqref:eq:viscous_system_d. To enforce
incompressibility eqref:eq:viscous_system_a we introduce the
streamfunction $\psi$:
\begin{equation}
u_v = -\frac{\partial \psi}{\partial z} \quad ; \quad w_v = \frac{\partial \psi}{\partial x} \qquad \left(\boldsymbol u = \nabla \times \left( \psi \boldsymbol e_y\right)\right)
\end{equation}

The curl of eqref:eq:momentum_viscous allows to get rid of pressure to
obtain a diffusion equation for the vorticity:
\begin{equation}
\frac{\partial \omega_y}{\partial t} = \nu \Delta \omega_y
\end{equation}
and vorticity and streamfunction are related through:
\begin{equation}
\Delta \psi = -\omega_y
\end{equation}
Here again we make use of variable separation. The forcing term
eqref:eq:vorticity_production_interface suggests the following form
for the vorticity and streamfunction fields:
\begin{subequations}
\begin{eqnarray}
&&\omega_y(x,z,t)=\Omega(z,t)\sin\left(kx\right)\\[1em]
&&\psi(x,z,t)=\Psi(z,t)\sin\left(kx\right) \label{eq:structure_psi}
\end{eqnarray}
\end{subequations}
This ansatz for $\omega_y$ and $\psi$ allows to rewrite the Poisson equation for $\psi$ as:
\begin{equation}
\frac{\partial^2 \Psi}{\partial z^2} - k^2 \Psi = - \Omega
\end{equation}
We solve this function by means of an appropriate Green's function
$G(z|z')$ satisfying:
\begin{equation}
\frac{\partial^2}{\partial z'^2}G(z|z') - k^2 G(z|z') = \delta(z-z')
\end{equation}
We are at liberty to choose appropriate boundary conditions for
$G(z|z')$ so let's choose them wisely. Standard manipulations of the
integral $\int_{-h}^0\Delta \Psi G \, \mathrm dz'$ yields:
\begin{equation}
\Psi(z,t)=-\int_{-h}^0\Omega(z',t)G(z|z')\,\mathrm dz' + \left[\Psi(z')\frac{\partial G}{\partial z'}\right]_{-h}^0 - \left[\frac{\partial \Psi}{\partial z'}G(z|z')\right]_{-h}^0
\end{equation}
Impermeability on both boundaries impose $\psi = \text{cst}$ at $z
=-h, 0$.
The structure of the field eqref:eq:structure_psi then
impose $\Psi = 0$ at these two boundaries, thereby cancelling the
first bracket. The second bracket would require the knowledge of $u_v$
at the boundaries, and then in turn of $\frac{\partial \phi}{\partial
x}$ to satisfy adherence.
But this can be circumvented by imposing $G=0$ at the boundaries, so that finally
\begin{equation}
\Psi(z,t)=-\int_{-h}^0\Omega(z',t)G(z|z')\,\mathrm dz' 
\end{equation}
and $G(z|z')$ satisfies
\begin{equation}
\begin{split}
&\frac{\partial^2}{\partial z'^2}G(z|z') - k^2 G(z|z')=\delta(z-z')\\[1em]
&G(z|-h)=G(z|0)=0\\[1em]
&G(z|z') \quad \text{continuous at}\, z=z'
\end{split}
\end{equation}
We note
\begin{equation}
G(z|z') = \left\{\begin{array}{c}
G^>(z|z') \quad \text{if}\quad z' > z\\
G^<(z|z') \quad \text{if}\quad z' < z
\end{array}\right.
\end{equation}
and find
\begin{subequations}
\begin{eqnarray}
G^<(z|z') &=& \frac{1}{k}\sinh\left(k\left(z'+h\right)\right) \frac{\sinh(kz)}{\sinh(kh)}\\[1em]
G^>(z|z') &=& \frac{1}{k}\sinh\left(kz'\right) \frac{\sinh\left(k\left(z+h\right)\right)}{\sinh(kh)}
\end{eqnarray}
\end{subequations}
So that $\Psi$ can be expressed with $\Omega$:
\begin{equation}
\begin{split}
\Psi(z,t) &= -\int_{-h}^z \frac{1}{k}\sinh\left(k\left(z'+h\right)\right)\frac{\sinh\left(kz\right)}{\sinh(kh)}\Omega(z',t)\,\mathrm dz'\\
 & - \int_{z}^0 \frac{1}{k}\sinh\left(kz'\right)\frac{\sinh\left(k\left(z+h\right)\right)}{\sinh(kh)}\Omega(z',t)\,\mathrm dz'
\end{split}
\label{eq:greenpsi}
\end{equation}
/In the limit of large depths/, this expression can be approximated by
\begin{equation}
\begin{split}
-2k\Psi(z,t) &\simeq e^{kz}\left(\int_{-\infty}^0 e^{kz'}\Omega\,\mathrm dz'+ \int_{0}^z e^{-kz'}\Omega\,\mathrm dz'\right)\\
 &- e^{-kz} \int_{-\infty}^z e^{kz'} \Omega \,\mathrm dz'
\end{split}
\end{equation}
which is eq (15) of Prosperetti's paper (the minus sign coming from
the change in coordinates from $y$ to $z$).

[[toc][Back to table of contents]]

* Designing a strategy to derive the solution

The strategy for finding the solution is a slight modification of
citeauthor:Prosperetti1976 's one, which can be outlined as:
1. Solve formally the diffusion equation for the vorticity using
   Laplace's transform and the boundary conditions $\Omega(0,t)$
   (vorticity production at the free surface) and $\Omega_h(t)$
   (bottom vorticity, still unknown).
2. On exploiting the connection between $\psi$ and $\omega$, reexpress
   the formal solution for the vorticity with the streamfunction.
3. Deduce the viscous contribution for the pressure $p_v$ with the
   help of the horizontal component of the momentum equation. $p_v$
   will therefore be expressed as a function of $\Omega_0$ (and
   thereby of the free surface amplitude and its time derivatives) and
   of $\Omega_h$ (still unknown),
4. The knowledge of the viscous contribution for the pressure and the
   streamfunction on the one hand, and of the potential velocity and
   pressure on the other hand, allows to write the normal stress jump
   condition as a single equation for $a(t)$ and its time derivatives,
   and $\Omega_h$ (still unknown),
5. Finally the /adherence condition/ allows to express the viscous
   tangential velocity at the bottom as a function of $\dot a(t)$. The
   value of $\Omega_h$ derives from this equation, and a formulation
   of the stress jump condition as a single equation for the only
   unknown $a(t)$ follows.

   [[toc][Back to table of contents]]

* Formal solution for the viscous vorticity and pressure

** Formal resolution of the diffusion equation for the vorticity

We start by solving, at least /formally/, the diffusion equation for the
vorticity $\Omega$:
\begin{equation}
\frac{\partial \Omega}{\partial t} = \nu \left( \frac{\partial^2 \Omega}{\partial z^2} - k^2 \Omega\right)
\label{eq:vorticity_diffusion}
\end{equation}
This partial diffferential equation can be turned into a (solvable)
ODE in Laplace' space.

Let's denote the Laplace transform of $\Omega$ as
\begin{equation}
\tilde \Omega(z,s) \equiv \mathcal L \left[\Omega\right] = \int_0^\infty \Omega(z,t) e^{-st} \, \mathrm dt
\end{equation}
and take an /initial vorticity-free/ condition $\Omega(z,0) = 0$:
\begin{equation}
\mathcal L \left[\frac{\partial\Omega}{\partial t}\right] = s \mathcal L \left[\Omega\right] - \cancel{\Omega(z,0)}
\end{equation}
It follows that in Laplace' space the diffusion equation
eqref:eq:vorticity_diffusion is rewritten:
\begin{equation}
\frac{\partial^2 \tilde\Omega}{\partial z^2} - \lambda^2 \tilde \Omega = 0,
\end{equation}
where $\lambda=\left(k^2 + \frac{s}{\nu}\right)^{1/2}$.

We saw earlier how the stress-free boundary condition forged the
vorticity production term at the free surface:
\begin{equation}
\tilde \Omega(0,s) = 2k\mathcal L\left[ \frac{\mathrm da}{\mathrm dt}\right]
\end{equation}
The bottom vorticity will ultimately be seen to arise from the no-slip
condition, but for now let's simply posit:
\begin{equation}
\Omega(-h,t) = \Omega_h(t).
\end{equation}
With these two boundary conditions, $\tilde\Omega$ is readily obtained:
\begin{equation}
\tilde \Omega(z,s) = 2 k \frac{\sinh\left(\lambda\left(z+h\right)\right)}{\sinh(\lambda h)}\mathcal L\left[\frac{\mathrm da}{\mathrm dt}\right] - \frac{\sinh(\lambda z)}{\sinh(\lambda h)} \tilde \Omega_h
\label{eq:OmegaLaplace}
\end{equation}
In the /large depth limit/, we recover Prosperetti's result:
\begin{equation}
\tilde \Omega(z,s) \underset{h\to\infty}{\to} \,2 k \mathcal L\left[\frac{\mathrm da}{\mathrm dt}\right] e^{\lambda z}
\end{equation}
** Viscous pressure

Symmetry considerations lead to search for the following form for the
viscous pressure:
\begin{equation}
p_v(x,z,t) = P(z,t) \cos (kx)
\end{equation}
To identify $P(z,t)$ we will exploit the horizontal projection for the
momentum equation. To make progress we first need to clarify the
expression for $\frac{\partial \Psi}{\partial t}$. Considering the
relation eqref:eq:greenpsi linking $\Psi$ to $\Omega$, we can formally
express $\frac{\partial \Psi}{\partial t}$ with a convolution involving $\frac{\partial \Omega}{\partial t}$. Further noting that
the latter term can be reformulated without time derivative with the
help of the diffusion equation eqref:eq:vorticity_diffusion, we can
then perform standard integral manipulations to obtain:
\begin{equation}
\frac{\partial \Psi}{\partial t} = \nu \frac{\sinh\left(k\left(z+h\right)\right)}{\sinh(kh)}\Omega(0,t) - \nu \frac{\sinh(kz)}{\sinh(kh)}\Omega_h(t) - \nu \Omega(z,t)
\end{equation}
This result can be directly used in the horizontal projection of the
momentum equation eqref:eq:momentum_viscous to deduce the expression of
the viscous contribution for the pressure:
\begin{equation}
P(z,t) = -\mu \frac{\cosh\left(k\left(z+h\right)\right)}{\sinh(kh)} \Omega(0,t) + \mu \frac{\cosh\left(kz\right)}{\sinh(kh)} \Omega_h(t)
\end{equation}

[[toc][Back to table of contents]]

* Normal stress jump condition

The normal stress jump condition eqref:eq:normalstressjump reads:
\begin{equation}
-p_p-p_v+ 2 \mu \frac{\partial w_p}{\partial z} + 2 \mu \frac{\partial w_v}{\partial z} = - \gamma \nabla \cdot \boldsymbol n
\end{equation}
at the free surface. Here, the linearised expression for the curvature
of the free surface is $\kappa\equiv\nabla\cdot\boldsymbol n \simeq
ak^2 \cos(kx)$, and a rapid inspection of the terms involved shows
that each has a $\cos(kx)$ dependence, which is simplified from now
on.  Injecting the previous expressions for pressure and velocity
(both viscous and potential), the surface condition is seen to adopt
the following damped-oscillator-like evolution equation:
\begin{equation}
\begin{split}
&\frac{\mathrm d^2a}{\mathrm dt^2} + 4 \nu k^2 \frac{\mathrm da}{\mathrm dt} + \omega_0^2 a - \frac{\nu k}{\cosh(kh)}\Omega_h \\
&- 2 \nu k^2 \int_{-h}^0\frac{\sinh\left(k\left(z'+h\right)\right)}{\cosh(kh)}\Omega(z',t)\,\mathrm dz' = 0,
\end{split}
\end{equation}
where we have introduced the inviscid normal mode pulsation for a
liquid layer oscillating due to surface tension and gravity:
\begin{equation}
\omega_0^2 = gk\tanh(kh)+\frac{\gamma}{\rho}k^3\tanh(kh).
\end{equation}

Further progress can be made in Laplace' space, where $\Omega$ is
determined in closed-form and $\Omega_h$ can be obtained exactly.

[[toc][Back to table of contents]]

* Bottom vorticity and governing equation for the amplitude

The adherence condition links the viscous and potential parts of the
velocity field at the bottom:
\begin{equation}
\left. u_p + u_v \right|_{z = -h} = 0
\label{eq:adherence_condition}
\end{equation}
As the potential structure depends on the surface velocity $\dot
a(t)$, we foresee that the bottom vorticity is a function of this
quantity as well. We explore this idea further in the following using
the Laplace transform.

** Bottom vorticity

The adherence condition eqref:eq:adherence_condition can be rewritten as:
\begin{equation}
\left.\frac{\partial \phi}{\partial x} - \frac{\partial \psi}{\partial z} \right|_{z=-h} = 0
\end{equation}
Upon using the previously derived expressions for $\phi$ and $\psi$,
we obtain the following form for adherence;
\begin{equation}
\int_{-h}^0\Omega(z',t)\sinh(kz')\,\mathrm dz'= \frac{\mathrm da}{\mathrm dt}
\end{equation}
The Laplace transform of this last equation is naturally:
\begin{equation}
\int_{-h}^0\tilde\Omega(z',t)\sinh(kz')\,\mathrm dz'= \mathcal L\left[\frac{\mathrm da}{\mathrm dt}\right]
\end{equation}
From the general solution for $\tilde\Omega$ we found earlier
eqref:eq:OmegaLaplace we deduce the expression for the bottom vorticity:
\begin{equation}
\tilde \Omega_h = \frac{2k\lambda\sinh(kh)-\left(\lambda^2+k^2\right) \sinh(\lambda h)}{\lambda\sinh(kh)\cosh(\lambda h) - k \sinh(\lambda h)\cosh(kh)} \mathcal L \left[\frac{\mathrm da}{\mathrm dt}\right].
\end{equation}

[[toc][Back to table of contents]]

bibliographystyle:abbrvnat
bibliography:suppl_note.bib
