# --------------------------------------------------------------------
#+TITLE:   Initial value problem for a viscous liquid layer
#+AUTHOR: Clément & Arnaud
#+STARTUP: indent latexpreview
#+LATEX_HEADER: \usepackage[text={18cm,26cm},centering]{geometry}
#+LATEX_HEADER: \usepackage{mathtools} \usepackage[round]{natbib} \usepackage{bm}  \setlength{\parindent}{0pt}
#+OPTIONS: toc:2 H:4
# --------------------------------------------------------------------

#+BEGIN_EXPORT html
<script type="text/x-mathjax-config">
MathJax.Extension['TeX/subequations'] = {
  version: "1.0.0",
  subEq: false,
  subNo: 0
};

MathJax.Hub.Register.StartupHook('TeX Jax Ready', function () {
  var TEX = MathJax.InputJax.TeX,
      TEXDEF = TEX.Definitions;
  var SUBEQ = MathJax.Extension['TeX/subequations'];
  var CONFIG = MathJax.Hub.config.TeX.equationNumbers;

  SUBEQ.oldFormat = CONFIG.formatNumber;
  CONFIG.formatNumber = function (n) {
    n = SUBEQ.oldFormat(n);
    if (!SUBEQ.subEq) return n;
    MathJax.Extension['TeX/AMSmath'].number--;
    var m = ++SUBEQ.subNo;
    return n + String.fromCharCode(0x60 + m);
  };

  TEXDEF.Add({
    environment: {
      subequations: ['SubEquationsBegin', 'SubEquationsEnd']
    }
  });

  TEX.Parse.Augment({
    SubEquationsBegin: function (begin) {
      SUBEQ.subEq = true;
      SUBEQ.subNo = 0;
      return begin;
    },
    SubEquationsEnd: function (begin, row) {
      SUBEQ.subEq = false;
      MathJax.Extension['TeX/AMSmath'].number++;
      return row;
    }
  });

  MathJax.Hub.Startup.signal.Post("TeX subequations Ready");
});
</script>
#+END_EXPORT

citet:Cortelezzi1981 propose a derivation of the equations governing
the initial value problem for a disturbed layer of viscous fluid,
considering both the effects of gravity and surface tension. We here
propose to revisit this paper by following an alternative derivation
based on the ideas of citet:Prosperetti1976. More specifically we
split the dynamical variables into a potential and a viscous
contribution. We restrict the analysis to a 2D setting, and note that
all the obtained results can be directly transposed to 3D, see
citet:Cortelezzi1981.


* Vorticity production at the free surface

The vorticity is directed along $\boldsymbol e_y$:
#+BEGIN_LATEX
\begin{equation}
\boldsymbol \omega = \left(
\begin{array}{c}
\omega_x \\
\omega_y \\
\omega_z
\end{array}
\right) =
\left.
\begin{array}{c}
\partial_x \\
0 \\
\partial_z
\end{array}
\right|
\times
\left|
\begin{array}{c}
u \\
0 \\
w
\end{array}
\right. =
\left(
\frac{\partial u}{\partial z} - 
\frac{\partial w}{\partial x}
\right) \boldsymbol e_y
\end{equation}
#+END_LATEX
Introducing the viscous shear stress $\tau_{xz} = \mu \left(
\frac{\partial u}{\partial z} + \frac{\partial w}{\partial x} \right)$
we can express the vorticity in terms of viscous shear stress:
\begin{equation}
\omega_y = \frac{\tau_{xz}}{\mu} - 2 \frac{\partial w}{\partial x}
\end{equation}
At the free surface, the tangential shear stress vanishes so
$\omega_y = - 2 \frac{\partial w}{\partial x}$ there.
This can be further reexpressed in terms of local free surface slope
variation with the help of the linearised kinematic condition $w =
\frac{\partial \eta}{\partial t}$, where $\eta(x,t)$ denotes the free
surface position. This relation reveals that vorticity production at
the free surface is equal to the time variation of the local slope:
\begin{equation}
\omega_y = - 2 \frac{\partial^2 \eta}{\partial x \partial t} \label{eq:vorticity_production_interface}
\end{equation}

* Problem splitting: the potential and the viscous

The equations governing the problem are associated with mass
conservation:
\begin{equation}
\nabla \cdot \boldsymbol u = 0,
\end{equation}
and momentum conservation:
\begin{equation}
\frac{\partial \boldsymbol u}{\partial t} = - \frac{1}{\rho} \nabla p + \nu \nabla^2\boldsymbol u - g \boldsymbol e_z.
\end{equation}

** Kinematical description of the interface

The interface is tracked at all times with the help of the color
function $F(x,z,t) = z - \eta(x,t)$ which cancels at the free
surface. We here look for /standing waves/ for which $\eta(x,t) = a(t) \cos(kx)$.  From this definition we can derive the expression of the
/linearised/ outward normal:
\begin{equation}
\boldsymbol n = \frac{\nabla F}{\|\nabla F\|} \simeq \left(k a(t) \sin (kx), 1 \right)
\end{equation}
This approximation is valid as long as the /amplitude/ (not the layer
thickness!) is small in front of the wavelength (i.e. $k a(t) \ll 1$).
Finally we require the function $F$ to satisfy the /kinematical
boundary condition/ $DF/Dt=0$. Linearisation yields to flatten this
condition at $z=0$:
\begin{equation}
\frac{\partial F}{\partial t} + w \frac{\partial F}{\partial z} = 0 \quad \text{on z = 0}
\end{equation}

** Dynamical boundary conditions

*** At the free surface

At the free surface, the normal stress jump is balanced by surface
tension:
\begin{equation}
-p + 2 \mu \frac{\partial w}{\partial z} = - \gamma \nabla \cdot
\boldsymbol n \quad \text{on} \quad F = 0
\end{equation}
and the shear stress is required to vanish (/free surface/ assumption):
\begin{equation}
\tau_{xz} = 0 \quad \text{on} \quad F = 0
\end{equation}

*** At the bottom

Impermeability and adherence impose:
\begin{equation}
u(y=-h) = w(y=-h) = 0
\end{equation}

** Potential and viscous parts

As demonstrated in citet:Prosperetti1976 it is convenient to split the
dynamical fields into a /potential/ and a /viscous/ part:
\begin{equation}
\boldsymbol u = \boldsymbol u_p + \boldsymbol u_v \quad ; \quad p = p_p + p_v
\end{equation}

**** $\rhd$ The potential problem.
:PROPERTIES:
:UNNUMBERED: t
:END:
$(\boldsymbol u_p,p_p)$ is solution to the following problem

\begin{subequations}
\begin{align}
&\boldsymbol u_p = \nabla \phi,\\[1em]
&\nabla^2 \phi = 0,\\[1em]
&\frac{\partial \boldsymbol u_p}{\partial t} = -\frac{1}{\rho} \nabla p_p - g \boldsymbol e_z,  \\[1em]
&\frac{\partial F}{\partial t} + w_p \frac{\partial F}{\partial z} = 0 \quad \text{on} \quad z = 0, \label{eq:kinematic_potential} \\[1em]
&\frac{\partial \phi}{\partial z} = 0  \quad \text{on} \quad z = -h.
\end{align}
\end{subequations}

Note that eqref:eq:kinematic_potential reads
\begin{equation}
w_p = \frac{\partial \eta}{\partial t} \label{eq:kinematic_potential_simplified}
\end{equation}
**** $\rhd$ The viscous correction.
:PROPERTIES:
:UNNUMBERED: t
:END:
$(\boldsymbol u_v,p_v)$ are then governed by the following equations:
\begin{subequations}
\begin{eqnarray}
&&\nabla \cdot \boldsymbol u_v = 0,\label{eq:viscous_system_a}\\[1em]
&&\frac{\partial \boldsymbol u_v}{\partial t} = -\frac{1}{\rho} \nabla p_v + \nu \nabla^2 \boldsymbol u_v,\label{eq:momentum_viscous}\\[1em]
&&w_v \frac{\partial F}{\partial z} = 0 \quad \text{on} \quad z = 0,\label{eq:kinematic_viscous}\\[1em]
&&w_v = u_p + u_v = 0  \quad \text{on} \quad z = -h.\label{eq:viscous_system_d}
\end{eqnarray}
\end{subequations}
and now the kinematical condition for the viscous problem eqref:eq:kinematic_viscous reads
\begin{equation}
w_v = 0  \quad \text{on} \quad z = 0
\end{equation}

** The potential solution

As we look for a standing wave-like solution, we search for a general
solution for the potential by exploiting variable separation. The
structure of the kinematical boundary condition
eqref:eq:kinematic_potential_simplified motivates the following
ansatz:
\begin{equation}
\phi(x,z,t) = F(z) \dot a(t) \cos (kx)
\end{equation}
eqref:eq:kinematic_potential_simplified and impermeability at the
bottom allow to precise $F(z)$:
\begin{equation}
\phi(x,z,t) = \frac{1}{k} \dot a(t) \underbrace{\frac{\cosh\left(k(z+h)\right)}{\sinh(kh)}}_{\underset{h\to\infty}{\to} \,e^{kz}}\cos(kx)
\end{equation}
The linearised form of Bernoulli equation  $p + \rho \frac{\partial
\phi}{\partial t} + \rho g z = 0$
associated with the expression for $\phi$ allows to deduce the pressure
field:
\begin{equation}
p_p(x,z,t) = -\rho\left(gz + \frac{1}{k} \frac{\mathrm d^2 a}{\mathrm dt^2} \frac{\cosh\left(k(z+h)\right)}{\sinh(kh)}\cos(kx)\right)
\end{equation}
These two expressions reduce to citeauthor:Prosperetti1976 expressions
in the deep layer limit. In the classic potential problem, $a(t)$ is
determined by the dynamical boundary condition on the free surface,
but as in the present problem both the viscous and the potential parts
are intertwined, this determination is postponed.

** The viscous solution

Let's turn now to the system of equations describing the viscous part
eqref:eq:viscous_system_a - eqref:eq:viscous_system_d. To enforce
incompressibility eqref:eq:viscous_system_a we introduce the
streamfunction $\psi$:
\begin{equation}
u_v = -\frac{\partial \psi}{\partial z} \quad ; \quad w_v = \frac{\partial \psi}{\partial x} \qquad \left(\boldsymbol u = \nabla \times \left( \psi \boldsymbol e_y\right)\right)
\end{equation}

The curl of eqref:eq:momentum_viscous allows to get rid of pressure to
obtain a diffusion equation for the vorticity:
\begin{equation}
\frac{\partial \omega_y}{\partial t} = \nu \Delta \omega_y
\end{equation}
and vorticity and streamfunction are related through:
\begin{equation}
\Delta \psi = -\omega_y
\end{equation}
Here again we make use of variable separation. The forcing term
eqref:eq:vorticity_production_interface suggests the following form
for the vorticity and streamfunction fields:
\begin{subequations}
\begin{eqnarray}
&&\omega_y(x,z,t)=\Omega(z,t)\sin\left(kx\right)\\[1em]
&&\psi(x,z,t)=\Psi(z,t)\sin\left(kx\right)
\end{eqnarray}
\end{subequations}
This ansatz for $\omega_y$ and $\psi$ allows to rewrite the Poisson equation for $\psi$ as:
\begin{equation}
\frac{\partial^2 \Psi}{\partial y^2} - k^2 \Psi = - \Omega
\end{equation}

bibliographystyle:abbrvnat
bibliography:suppl_note.bib
